spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=utf8&useTimezone=true&serverTimezone=CTT&useUnicode=true&useSSL=false
      username: root
      password: '0506'
      max-active: 10
      min-idle: 3
      initial-size: 3
      validation-query: select 1 from DUAL
      filter:
        wall:
          enabled: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          db-type: mysql
  redis:
    host: 192.168.20.196
    port: 6379
    database: 5
  rabbitmq:
    addresses: 192.168.109.129
    password: user_01
    username: user_01
    port: 5672
    virtual-host: /miaosha-goods
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
        default-requeue-rejected: false
  jackson:
    time-zone: GMT+8
